global:
  resolve_timeout: 5m
  smtp_smarthost: smtp.gmail.com:587
  smtp_from: benharbfarah85@gmail.com
  smtp_auth_username: benharbfarah85@gmail.com
  smtp_auth_password: nwxx yjoy iuca yjuc
  smtp_require_tls: true

templates:
  - /etc/alertmanager/templates/*.tmpl

route:
  receiver: email-alerts
  group_by:
    - alertname
    - service
    - severity
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h

receivers:
  - name: email-alerts
    email_configs:
      - to: benharbfarah85@gmail.com
        send_resolved: true
        text: '{{ template "email.default.text" . }}'
        html: '{{ template "email.default.html" . }}'
        headers:
          Subject: >-
            [{{ .Status | toUpper }}{{ if gt (len .Alerts.Firing) 0 }}:{{ len .Alerts.Firing }}{{ end }}] {{ .CommonLabels.alertname }}{{ if .CommonLabels.service }} ({{ .CommonLabels.service }}){{ end }}

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal:
      - alertname
      - service
